# 12. 넘파이 패키지

## 12.1	array, numpy, matplotlib 패키지 개요

### 12.1.1 array 패키지

### 12.1.2 numpy 패키지

### 12.1.3 numpy.random 패키지

### 12.1.4 matplotlib 패키지

## 12.2	“array” 패키지 사용하기

<table class="docutils align-default">
<colgroup>
<col style="width: 15%">
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>형 코드</p></th>
<th class="head"><p>C 형</p></th>
<th class="head"><p>파이썬 형</p></th>
<th class="head"><p>사이즈(바이트)</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">'b'</span></code></p></td>
<td><p>signed char</p></td>
<td><p>int</p></td>
<td><p>1</p></td>
</tr>
    
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">'B'</span></code></p></td>
<td><p>unsigned char</p></td>
<td><p>int</p></td>
<td><p>1</p></td>
</tr>

<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">'u'</span></code></p></td>
<td><p>wchar_t</p></td>
<td><p>유니코드 문자</p></td>
<td><p>2</p></td>
</tr>

<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">'h'</span></code></p></td>
<td><p>signed short</p></td>
<td><p>int</p></td>
<td><p>2</p></td>
</tr>

<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">'H'</span></code></p></td>
<td><p>unsigned short</p></td>
<td><p>int</p></td>
<td><p>2</p></td>
</tr>

<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">'i'</span></code></p></td>
<td><p>signed int</p></td>
<td><p>int</p></td>
<td><p>2</p></td>
</tr>

<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">'I'</span></code></p></td>
<td><p>unsigned int</p></td>
<td><p>int</p></td>
<td><p>2</p></td>
</tr>

<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">'l'</span></code></p></td>
<td><p>signed long</p></td>
<td><p>int</p></td>
<td><p>4</p></td>
</tr>

<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">'L'</span></code></p></td>
<td><p>unsigned long</p></td>
<td><p>int</p></td>
<td><p>4</p></td>
</tr>

<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">'q'</span></code></p></td>
<td><p>signed long long</p></td>
<td><p>int</p></td>
<td><p>8</p></td>
</tr>

<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">'Q'</span></code></p></td>
<td><p>unsigned long long</p></td>
<td><p>int</p></td>
<td><p>8</p></td>
</tr>

<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">'f'</span></code></p></td>
<td><p>float</p></td>
<td><p>float</p></td>
<td><p>4</p></td>
</tr>

<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">'d'</span></code></p></td>
<td><p>double</p></td>
<td><p>float</p></td>
<td><p>8</p></td>
</tr>
</tbody>
</table>

In [1]:
import array

In [2]:
a = array.array('h', [1, 2, 3])
a

array('h', [1, 2, 3])

In [3]:
a = array.array('h', range(1000))
a

array('h', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219

In [6]:
a = array.array('l', range(1_000_000))

## 12.3	numpy 패키지를 내려받고 탑재하기

## 12.4 numpy 소개하기: 1부터 100만까지 더하기

In [7]:
import numpy as np

In [8]:
a_list = list(range(1, 1_000_001))
print(sum(a_list))

500000500000


In [9]:
a = np.arange(1, 1_000_001)
print(sum(a))

500000500000


In [24]:
import numpy as np
from time import time

def benchmarks(n):
    t1 = time()
    a_list = list(range(1, n + 1)) 	# Old style!
    tot = sum(a_list)
    t2 = time()
    elapsed_time_1 = t2 - t1
    print('Time taken by Python is {0:6.4f}'.format(elapsed_time_1))

    t1 = time()
    a = np.arange(1, n + 1) 		# Numpy!
    tot = np.sum(a)
    t2 = time()
    elapsed_time_2 = t2 - t1    
    print('Time taken by numpy is {0:6.4f}'.format(t2 - t1))
    
    print('Time difference rate is {0:5.3f}'.format(elapsed_time_1 / elapsed_time_2))    

In [25]:
benchmarks(10_000_000)

Time taken by Python is 0.1811
Time taken by numpy is 0.0150
Time difference rate is 12.100


In [26]:
import numpy as np
from time import time

def benchmarks(n):
    a_list = list(range(1, n + 1)) 	# Old style!
    t1 = time()
    tot = sum(a_list)
    t2 = time()
    elapsed_time_1 = t2 - t1
    print('Time taken by Python is {0:6.4f}'.format(elapsed_time_1))

    a = np.arange(1, n + 1) 		# Numpy!
    t1 = time()
    tot = np.sum(a)
    t2 = time()
    elapsed_time_2 = t2 - t1    
    print('Time taken by numpy is {0:6.4f}'.format(t2 - t1))
    
    print('Time difference rate is {0:5.3f}'.format(elapsed_time_1 / elapsed_time_2))    

In [27]:
benchmarks(10_000_000)

Time taken by Python is 0.0463
Time taken by numpy is 0.0058
Time difference rate is 8.032


## 12.5	numpy 배열 만들기

- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html



Tndarray
The transposed array.

databuffer
Python buffer object pointing to the start of the array’s data.

dtypedtype object
Data-type of the array’s elements.

flagsdict
Information about the memory layout of the array.

flatnumpy.flatiter object
A 1-D iterator over the array.

imagndarray
The imaginary part of the array.

realndarray
The real part of the array.

sizeint
Number of elements in the array.

itemsizeint
Length of one array element in bytes.

nbytesint
Total bytes consumed by the elements of the array.

ndimint
Number of array dimensions.

shapetuple of ints
Tuple of array dimensions.

stridestuple of ints
Tuple of bytes to step in each dimension when traversing an array.

ctypesctypes object
An object to simplify the interaction of the array with the ctypes module.

basendarray
Base object if memory is from some other object.

### 12.5.1 array 함수 (array로 변환)

In [31]:
import numpy as np

In [54]:
a = np.array([1, 2, 3])
print(a)
print("-" * 80)
print("{0:>10}: {1}".format("a.T", a.T))
print("{0:>10}: {1}".format("a.data", a.data))
print("{0:>10}: {1}".format("a.dtype", a.dtype))
print("{0:>10}: {1}".format("a.flat", a.flat)) # A 1-D iterator over the array

print("{0:>10}: {1}".format("a.imag", a.imag))
print("{0:>10}: {1}".format("a.real", a.real))

print("{0:>10}: {1}".format("a.size", a.size))
print("{0:>10}: {1}".format("a.itemsize", a.itemsize)) # Length of one array element in bytes
print("{0:>10}: {1}".format("a.nbytes", a.nbytes)) # Number of elements in the array

print("{0:>10}: {1}".format("a.ndim", a.ndim)) # Number of array dimensions.
print("{0:>10}: {1}".format("a.shape", a.shape)) # Tuple of array dimensions.

print("{0:>10}: {1}".format("a.strides", a.strides)) # Tuple of bytes to step in each dimension when traversing an array.

print("{0:>10}: {1}".format("a.ctypes", a.ctypes)) # An object to simplify the interaction of the array with the ctypes module
print("{0:>10}: {1}".format("a.base", a.base)) # Base object if memory is from some other object

print("{0:>10}:==>\n{1}".format("a.flags", a.flags))

[1 2 3]
--------------------------------------------------------------------------------
       a.T: [1 2 3]
    a.data: <memory at 0x7f8258abb408>
   a.dtype: int64
    a.flat: <numpy.flatiter object at 0x7f825286aa00>
    a.imag: [0 0 0]
    a.real: [1 2 3]
    a.size: 3
a.itemsize: 8
  a.nbytes: 24
    a.ndim: 1
   a.shape: (3,)
 a.strides: (8,)
  a.ctypes: <numpy.core._internal._ctypes object at 0x7f82381c16d8>
    a.base: None
   a.flags:==>
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [55]:
a = np.array([[1, 2, 3], [10, 20, 30], [0, 0, -1]])
print(a)
print("-" * 80)
print("{0:>10}: {1}".format("a.T", a.T))
print("{0:>10}: {1}".format("a.data", a.data))
print("{0:>10}: {1}".format("a.dtype", a.dtype))
print("{0:>10}: {1}".format("a.flat", a.flat)) # A 1-D iterator over the array

print("{0:>10}: {1}".format("a.imag", a.imag))
print("{0:>10}: {1}".format("a.real", a.real))

print("{0:>10}: {1}".format("a.size", a.size))
print("{0:>10}: {1}".format("a.itemsize", a.itemsize)) # Length of one array element in bytes
print("{0:>10}: {1}".format("a.nbytes", a.nbytes)) # Number of elements in the array

print("{0:>10}: {1}".format("a.ndim", a.ndim)) # Number of array dimensions.
print("{0:>10}: {1}".format("a.shape", a.shape)) # Tuple of array dimensions.

print("{0:>10}: {1}".format("a.strides", a.strides)) # Tuple of bytes to step in each dimension when traversing an array.

print("{0:>10}: {1}".format("a.ctypes", a.ctypes)) # An object to simplify the interaction of the array with the ctypes module
print("{0:>10}: {1}".format("a.base", a.base)) # Base object if memory is from some other object

print("{0:>10}:==>\n{1}".format("a.flags", a.flags))

[[ 1  2  3]
 [10 20 30]
 [ 0  0 -1]]
--------------------------------------------------------------------------------
       a.T: [[ 1 10  0]
 [ 2 20  0]
 [ 3 30 -1]]
    a.data: <memory at 0x7f8258abe1f8>
   a.dtype: int64
    a.flat: <numpy.flatiter object at 0x7f8262829000>
    a.imag: [[0 0 0]
 [0 0 0]
 [0 0 0]]
    a.real: [[ 1  2  3]
 [10 20 30]
 [ 0  0 -1]]
    a.size: 9
a.itemsize: 8
  a.nbytes: 72
    a.ndim: 2
   a.shape: (3, 3)
 a.strides: (24, 8)
  a.ctypes: <numpy.core._internal._ctypes object at 0x7f82381c1a20>
    a.base: None
   a.flags:==>
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [12]:
a = np.array([[1, 2, 3], [10, 20, 300]])
a

array([[  1,   2,   3],
       [ 10,  20, 300]])

In [13]:
a = np.array([[1, 2, 3], [10, 20, 300, 4]])
a

C:\Users\gilbut\anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([1, 2, 3]), list([10, 20, 300, 4])], dtype=object)

### 12.5.2 arange 함수

In [56]:
import numpy as np
a = np.arange(1, 1000001) 	# 100만개 항목으로 구성된 배열 생성

### 12.5.3	linspace 함수

In [57]:
import numpy as np
a = np.linspace(0, 1.0, num=5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [58]:
import numpy as np
a = np.linspace(0, 1.0, num=5, endpoint=False)
a

array([0. , 0.2, 0.4, 0.6, 0.8])

In [16]:
a = np.linspace(0, 1.0, num=6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
np.linspace(1, 5, num=5, dtype=np.int16)

array([1, 2, 3, 4, 5], dtype=int16)

### 12.5.4 empty 함수

In [18]:
import numpy as np
a = np.empty((2, 2), dtype='int16')
a

array([[    0,     0],
       [    0, 16368]], dtype=int16)

In [19]:
a = np.empty((3, 2), dtype='float32')
a

array([[3.3454865e+31, 8.6880505e-43],
       [0.0000000e+00, 0.0000000e+00],
       [1.8367379e-40,           nan]], dtype=float32)

### 12.5.5	eye 함수

In [20]:
a = np.eye(4, dtype='int')
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [21]:
a = np.eye(6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### 12.5.6 ones 함수

In [22]:
import numpy as np
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a = np.ones((2, 2, 3), dtype=np.int16)
a

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [24]:
a = np.ones(6, dtype=np.bool)
a

array([ True,  True,  True,  True,  True,  True])

### 12.5.7	zeros 함수

In [25]:
import numpy as np
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
a = np.zeros((2, 2, 3), dtype=np.int16)
a

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [27]:
a = np.zeros(5, dtype=np.bool)
a

array([False, False, False, False, False])

### 12.5.8 full 함수

In [28]:
import numpy as np
a = np.full((2, 2), 3.14)
a

array([[3.14, 3.14],
       [3.14, 3.14]])

In [29]:
a = np.full(8, 100)
a

array([100, 100, 100, 100, 100, 100, 100, 100])

In [59]:
a = np.full(5,'ken')
a

array(['ken', 'ken', 'ken', 'ken', 'ken'], dtype='<U3')

In [60]:
a[0] = 'tommy'
a[0]

'tom'

In [61]:
a

array(['tom', 'ken', 'ken', 'ken', 'ken'], dtype='<U3')

### 12.5.9 copy 함수

In [32]:
import numpy as np
b_arr = np.copy(a)
b_arr

array(['tom', 'ken', 'ken', 'ken', 'ken'], dtype='<U3')

### 12.5.10 fromfunction 함수

In [62]:
import numpy as np

def simple(n):
    return n + 1

a = np.fromfunction(simple, (5,), dtype='int32')
a

array([1, 2, 3, 4, 5], dtype=int32)

In [63]:
a = np.fromfunction(lambda n:n+1, (5,), dtype='int32')
a

array([1, 2, 3, 4, 5], dtype=int32)

In [64]:
def add_it(r, c):
    return r + c

a = np.fromfunction(add_it, (3, 3), dtype='int32')
a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]], dtype=int32)

In [65]:
a = np.fromfunction(lambda r, c:r+c, (3, 3), dtype='int')
a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [68]:
a = np.fromfunction(lambda _, r, c:r+c, (2, 3, 3), dtype='int')
a

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]]])

In [69]:
a = np.fromfunction(lambda r, c: 1, (3, 3), dtype='int')
a

1

## 12.6	예시:  곱셈표 만들기

In [70]:
import numpy as np

def multy(r, c):
    return (r + 1) * (c + 1)

a = np.fromfunction(multy, (10, 10), dtype=np.int16)
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [72]:
a = np.fromfunction(lambda r,c: (r + 1) * (c + 1), (10, 10), dtype=np.int16)
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [76]:
s = str(a)
s = s.replace('[', '')
s = s.replace(']', '')
s = ' ' + s

In [77]:
print(s)

   1   2   3   4   5   6   7   8   9  10
   2   4   6   8  10  12  14  16  18  20
   3   6   9  12  15  18  21  24  27  30
   4   8  12  16  20  24  28  32  36  40
   5  10  15  20  25  30  35  40  45  50
   6  12  18  24  30  36  42  48  54  60
   7  14  21  28  35  42  49  56  63  70
   8  16  24  32  40  48  56  64  72  80
   9  18  27  36  45  54  63  72  81  90
  10  20  30  40  50  60  70  80  90 100


## 12.7 numpy 배열의 배치 연산

In [80]:
import numpy as np

A = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
A = np.fromfunction(lambda r, c: r * 4 + c, (4, 4))
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [84]:
B = np.eye(4, dtype='int16')
print(B)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [85]:
C = A * 10
print(C)

[[  0.  10.  20.  30.]
 [ 40.  50.  60.  70.]
 [ 80.  90. 100. 110.]
 [120. 130. 140. 150.]]


In [86]:
C = A * A
print(C)

[[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]
 [144. 169. 196. 225.]]


In [87]:
print(C.reshape((2,8)))

[[  0.   1.   4.   9.  16.  25.  36.  49.]
 [ 64.  81. 100. 121. 144. 169. 196. 225.]]


In [89]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [88]:
C = A * B
print(C)

[[ 0.  0.  0.  0.]
 [ 0.  5.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 15.]]


## 12.8 numpy의 조각을 정렬하기

In [90]:
A = np.arange(1, 11)
print(A)

[ 1  2  3  4  5  6  7  8  9 10]


In [91]:
print(A[2:5])

[3 4 5]


In [92]:
A[2:5] = 0
print(A)

[ 1  2  0  0  0  6  7  8  9 10]


In [93]:
A[2:5] += 100
print(A)

[  1   2 100 100 100   6   7   8   9  10]


In [94]:
A = np.arange(1, 11)
A[2:5] *= [100, 200, 300]
A

array([   1,    2,  300,  800, 1500,    6,    7,    8,    9,   10])

In [95]:
A = np.arange(51)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [96]:
A[1] = 0
A[2 * 2::2] = 0
print(A)

[ 0  0  2  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0 21  0 23
  0 25  0 27  0 29  0 31  0 33  0 35  0 37  0 39  0 41  0 43  0 45  0 47
  0 49  0]


In [97]:
A[3 * 3::3] = 0
print(A)

[ 0  0  2  3  0  5  0  7  0  0  0 11  0 13  0  0  0 17  0 19  0  0  0 23
  0 25  0  0  0 29  0 31  0  0  0 35  0 37  0  0  0 41  0 43  0  0  0 47
  0 49  0]


In [98]:
A[5 * 5::5] = 0
A[7 * 7::7] = 0
print(A)

[ 0  0  2  3  0  5  0  7  0  0  0 11  0 13  0  0  0 17  0 19  0  0  0 23
  0  0  0  0  0 29  0 31  0  0  0  0  0 37  0  0  0 41  0 43  0  0  0 47
  0  0  0]


In [99]:
my_prime_list = [i for i in A if i > 0]

In [101]:
A > 0

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False])

- Boolean Numpy Array
  - 임의의 Numpy 배열 A의 인덱싱 연산에 활용되어 A 자체에 마스크(mask)로 적용

In [100]:
P = A[A > 0]
print(P)

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47]


## 12.9 다차원 슬라이싱

In [61]:
A = np.arange(1,17).reshape((4,4))
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [62]:
print(A[1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
A[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [64]:
G = np.zeros((6, 6))
G[1:4, 2] = 1
print(G)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [65]:
print(G[1:4, 1:4])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


- 행과 열 및 차원 매핑
<img src="https://cdn-coiao.nitrocdn.com/CYHudqJZsSxQpAPzLkHFOkuzFKDpEHGF/assets/static/optimized/wp-content/uploads/2018/11/d5219fff905b4a4c5a8a17d34b6808b5.numpy-arrays-have-axes.png" style="width:50%"/>

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcSoMOs%2Fbtqt0a2Dc2y%2FQhkfwhiWqeUKvNfsM2H29K%2Fimg.png" style="width:50%"/>
<br/>
<br/>

<img src="https://scipy-lectures.org/_images/numpy_indexing.png" style="width:50%"/>

## 12.10	불리언 배열: 넘파이에 마스킹하기!

In [107]:
B = np.arange(1,10).reshape(3,3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [108]:
B1 = B > 4
B1

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [109]:
print(B * (B > 4))

[[0 0 0]
 [0 5 6]
 [7 8 9]]


In [110]:
print(B[B > 7])

[8 9]


In [111]:
print(B[B % 3 == 1])

[1 4 7]


In [112]:
B2 = (B > 2) & (B < 7) 		# "AND" 연산
print(B2)

[[False False  True]
 [ True  True  True]
 [False False False]]


In [113]:
print(B[B2])

[3 4 5 6]


In [114]:
print(B[ (B == 1) | (B > 6)]) 	# ‘OR’ 연산자

[1 7 8 9]


## 12.11 numpy와 에라토스테네스의 체

In [125]:
def sieve(n):
    b_list = [True] * (n + 1)
    b_list[0:2] = [False, False] # 일반 파이썬 리스트에서 슬라이싱 할당은 동일 사이즈로만 가능
    for i in range(2, n+1):
        if b_list[i]:
            for j in range(i*i, n+1, i):
                b_list[j] = False
    primes = [i for i in range(2, n+1) if b_list[i]]
    return primes

In [126]:
sieve(50)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

In [136]:
import numpy as np

def np_sieve(n):
    # B 생성, 모든 항목을 True로 설정한다.
    B = np.ones(n + 1, dtype=np.bool)
    B[0:2] = False
    for i in range(2, n + 1):
        if B[i]:
            B[i*i: n+1: i] = False
    return np.arange(n + 1)[B]

In [137]:
np_sieve(50)

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47])

In [138]:
import time

- 1000까지 소수 검출 속도 비교

In [144]:
t1 = time.time() * 1000
sieve(1_000)
t2 = time.time() * 1000
print('sieve took', t2-t1, 'milliseconds.')

sieve took 0.23974609375 milliseconds.


In [145]:
t1 = time.time() * 1000
np_sieve(1_000)
t2 = time.time() * 1000
print('np_sieve took', t2-t1, 'milliseconds.')

np_sieve took 0.280029296875 milliseconds.


- 10000000 까지 소수 검출 속도 비교

In [146]:
t1 = time.time() * 1000
sieve(10_000_000)
t2 = time.time() * 1000
print('sieve took', t2-t1, 'milliseconds.')

sieve took 2544.094970703125 milliseconds.


In [147]:
t1 = time.time() * 1000
np_sieve(10_000_000)
t2 = time.time() * 1000
print('np_sieve took', t2-t1, 'milliseconds.')

np_sieve took 908.71826171875 milliseconds.


In [130]:
import numpy as np
import time

def np_sieve(n):
    t1 = time.time() * 1000
    B = np.ones(n + 1, dtype=np.bool)
    B[0:2] = False
    for i in range(2, n + 1):
        if B[i]:
            B[i*i: n+1: i] = False
    P = np.arange(n + 1)[B]
    t2 = time.time() * 1000
    print('np_sieve took', t2-t1, 'milliseconds.')

## 12.12 numpy 통계 구하기 – 표준 편차

In [148]:
import numpy as np
import numpy.random as ran
A = ran.rand(10)
print(A)

[0.90591864 0.21635616 0.14701949 0.91959164 0.89433352 0.25341854
 0.37597756 0.25475595 0.87156539 0.255875  ]


In [149]:
A = ran.rand(100000)

In [150]:
import numpy as np
import numpy.random as ran
A = ran.random(100000)
np.mean(A)

0.5009536276860572

In [151]:
np.sum(A)

50095.36276860572

In [152]:
np.median(A)

0.502191169419102

In [153]:
np.std(A)

0.28873306812708643

In [154]:
import numpy as np
import time
import numpy.random as ran

def get_std1(ls):
    t1 = time.time()
    m = sum(ls)/len(ls)
    ls2 = [(i - m) ** 2 for i in ls]
    sd = (sum(ls2)/len(ls2)) ** .5
    t2 = time.time()
    print('Python took', t2-t1)

def get_std2(A):
    t1 = time.time()
    A2 = (A - np.mean(A)) ** 2
    result = (np.mean(A2)) ** .5
    t2 = time.time()
    print('Numpy took', t2-t1)

def get_std3(A):
    t1 = time.time()
    result = np.std(A)
    t2 = time.time()
    print('np.std took', t2-t1)

A = ran.rand(1000000)
get_std1(A)
get_std2(A)
get_std3(A)

Python took 0.6536650657653809
Numpy took 0.005223989486694336
np.std took 0.0045299530029296875


## 12.13 numpy 행과 열 가져오기

In [84]:
import numpy as np
import numpy.random as ran
A = ran.randint(1, 20, (3, 4))
print(A)

[[ 4 14 15  7]
 [16 19 16  5]
 [ 8 16 12 15]]


In [85]:
np.mean(A)

12.25

In [86]:
np.sum(A)

147

In [87]:
np.std(A) 		# 표준 편차

4.763139720814412

In [88]:
B = np.fromfunction(lambda r,c: c, (4, 5), dtype=np.int32)
print(B)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


- sum() & axis
<img src="https://blog.kakaocdn.net/dn/uUre0/btqZQHVLmxW/3aTi3jUKUsXzij3PC1Hj8k/img.png" style="width:50%"/>


In [89]:
np.sum(B, axis = 0) 		# 행, 열의 합계.

array([ 0,  4,  8, 12, 16])

In [90]:
np.sum(B, axis = 1) 		# 열, 행의 합계.

array([10, 10, 10, 10])

In [91]:
B = np.fromfunction(lambda r,c:c, (4, 5), dtype=np.int32)
print(B)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [92]:
B_rows = np.sum(B, axis = 1)
B_rows

array([10, 10, 10, 10])

In [93]:
B1 = np.c_[B, B_rows]
print(B1)

[[ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]]


In [94]:
B_cols = np.sum(B1, axis = 0)
B_cols

array([ 0,  4,  8, 12, 16, 40])

In [95]:
B2 = np.r_[B1, [B_cols]]
print(B2)

[[ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  1  2  3  4 10]
 [ 0  4  8 12 16 40]]


In [161]:
def spreadsheet(A):
    AC = np.sum(A, axis = 1)
    A2 = np.c_[A, AC]
    AR = np.sum(A2, axis = 0)
    return np.r_[A2, [AR] ]

In [162]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [163]:
print(spreadsheet(arr))

[[  0   1   2   3   4  10]
 [  5   6   7   8   9  35]
 [ 10  11  12  13  14  60]
 [ 15  18  21  24  27 105]]
